name: 'Perform string operations'
description: 'You will be perform string functions'
inputs:
  string_to_process:     
    required: true
    default: "Test"
  function_name:     
    required: true
    default: "Test"
outputs:
  result:
    description: 'converted string'  
runs:
  using: 'node16'
  main: 'index.js'
